on: [push, pull_request]
name: Go-Paseto
permissions:
  contents: read
jobs:
  test:
    name: Units
    strategy:
      fail-fast: false
      matrix:
        go: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v2

      - name: Run tests
        run: go test -race -v

  vectors-not-stale:
    name: Check Test Vectors Up To Date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for updates
        run: |
          cd test-vectors
          rm *
          wget https://raw.githubusercontent.com/paseto-standard/test-vectors/master/v{1..4}.json
          git diff --exit-code